### ISSUE TITLE
Default camera is the wide-angle

### ISSUE THREAD

**Issue by phr00t** [Adriankhl/opencameraR#1]
When opening the app, the default zoom is 1.0x. Unfortunately, this uses the "wide angle" camera which isn't as good as the "normal" camera. I have to zoom in a little bit, to 1.03x, to get the "normal" camera. You can confirm this by covering up the wide-angle lens with your finger and see when it switches.

The default 1.0x zoom should use the "normal" camera, not the wide-angle one. The "wide-angle" should only activate at <1.0x zoom.

EDIT: It looks like displaying the Zoom +/- buttons allows you to hit the + button once to switch to the normal camera, still at zoom 1.0x. So, looks like the main problem is "wide-angle" camera being the default on open.

**Comment by Adriankhl** [comment]
Thanks for the report, I knew the default zoom looks bad but I thought it was the problem of opencamera itself. Now it should be fixed.

**Comment by phr00t** [comment]
Excellent work, it works! Thank you!
